import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { AuthProvider } from "@/context/AuthContext";
import { Inter } from "next/font/google";

 const inter = Inter({
  subsets: ["latin"],
  display: "swap", 
});

export const metadata: Metadata = {
  title: "Newsletter.AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="${inter.className} min-h-screen bg-gray-50 text-gray-900 ">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}